name: Run R script

on: 
  push:
  # schedule:
  # - cron: '0 */24 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: 
      PIP_NO_WARN_SCRIPT_LOCATION: false
      RETICULATE_AUTOCONFIGURE: 'FALSE'
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install Python and instaloader
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('rstudio/reticulate')"
          Rscript -e "reticulate::install_miniconda()"
          Rscript -e "reticulate::conda_create('r-reticulate', packages = c('python==3.6.9'))"
          Rscript -e "reticulate::py_install(c('instaloader'), pip = T, envname = NULL)"
      - name: Run R script
        run: Rscript script.R
      - name: Commit results
        run: |
          git add -A || echo "No changes to commit"
          git commit --allow-empty -m 'gHA build: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
