name: Run R script

on: 
  push:
  # schedule:
  # - cron: '0 */24 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: 
      PIP_NO_WARN_SCRIPT_LOCATION: false
      RETICULATE_AUTOCONFIGURE: 'FALSE'
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.9'
      - name: Install dependencies
        run: python -m pip install --upgrade pip instaloader
      - name: Run Py script
        run: python script.py
        env: # Or as an environment variable
          INSTAGRAM_PW: ${{ secrets.INSTAGRAM_PW }}
          INSTAGRAM_LOGIN: ${{ secrets.INSTAGRAM_LOGIN }}
      - name: Commit results
        run: |
          git config --global user.email "fabio.votta@gmail.com"
          git config --global user.name "favstats"
          git add -A
          git commit --allow-empty -m 'gHA build: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"